from app.api.v1 import auth
from app.api.v1 import user
from app.api.v1 import import_json
from app.api.v1 import hospital
from app.api.v1 import police
from app.api.v1 import apartment
from app.api.v1 import upload_file
from app.api.v1 import place
from app.api.v1 import history
from app.api.v1 import department
from app.api.v1 import employee